export { Hero } from './Hero'
export { ForWho } from './ForWho'
export { HowItWorks } from './HowItWorks'
export { Roadmap } from './Roadmap'
export { WhyDifferent } from './WhyDifferent'
export { Features } from './Features'
export { LabPartner } from './LabPartner'
export { SocialProof } from './SocialProof'
export { Alternatives } from './Alternatives'
export { FAQ } from './FAQ'
export { EarlyAccess } from './EarlyAccess'
export { Download } from './Download'
export { Founder } from './Founder'

